-- Run once in the Supabase SQL Editor, or apply with the Supabase CLI.
-- Existing tables with these names cause an error rather than being overwritten.
begin;

create table public.categories (
  id integer generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 150),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

create table public.projects (
  id integer generated always as identity primary key,
  request_id uuid not null unique,
  created_by uuid not null,
  title text not null check (char_length(btrim(title)) between 1 and 150),
  slug text not null constraint projects_slug_key unique
    check (char_length(slug) <= 180 and slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  category_id integer not null references public.categories(id) on delete restrict,
  description text not null default '' check (char_length(description) <= 5000),
  location text not null default '' check (char_length(location) <= 150),
  year integer not null check (year between 2000 and 2100),
  status text not null check (status in ('design', 'in_progress', 'completed')),
  created_at timestamptz not null default now()
);
create index projects_category_id_idx on public.projects(category_id);
create index projects_created_at_idx on public.projects(created_at desc, id desc);

create table public.project_media (
  id integer generated always as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  kind text not null check (kind in ('main', 'gallery', 'application', 'video')),
  position integer not null check (position between 0 and 11),
  object_path text not null unique,
  check (kind not in ('main', 'video') or position = 0),
  unique(project_id, kind, position)
);

alter table public.categories enable row level security;
alter table public.projects enable row level security;
alter table public.project_media enable row level security;

-- Portfolio records are public. The only write entry point is the validated RPC below.
revoke all on public.categories, public.projects, public.project_media from anon, authenticated;
grant select on public.categories, public.projects, public.project_media to anon, authenticated;
create policy categories_public_read on public.categories for select to anon, authenticated using (true);
create policy projects_public_read on public.projects for select to anon, authenticated using (true);
create policy project_media_public_read on public.project_media for select to anon, authenticated using (true);

insert into public.categories (id, name, slug) values
  (1, 'Bioclimatic Sistemleri', 'bioclimatic-sistemleri'),
  (2, 'Tente ve Gölgelendirme', 'tente-ve-golgelendirme'),
  (3, 'Cam Tavan Sistemleri', 'cam-tavan-sistemleri'),
  (4, 'Giyotin Sistemleri', 'giyotin-sistemleri'),
  (5, 'Isıcamlı Sürme Sistemleri', 'isicamli-surme-sistemleri'),
  (6, 'Cam Balkon Sistemleri', 'cam-balkon-sistemleri'),
  (7, 'Rüzgar Kırıcı Sistemleri', 'ruzgar-kirici-sistemleri');
select pg_catalog.setval(pg_catalog.pg_get_serial_sequence('public.categories', 'id'), 7, true);

-- One public portfolio bucket. App/RPC enforce 10 MB images, 100 MB video, 150 MB total.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('project-media', 'project-media', true, 104857600,
  array['image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/webm']);

create policy portfolio_media_insert on storage.objects for insert to authenticated
with check (
  bucket_id = 'project-media'
  and split_part(name, '/', 1) = (select auth.uid())::text
  and name ~ '^[0-9a-f-]{36}/[0-9a-f-]{36}/(main|gallery|application|video)-[0-9]+\.(jpg|png|webp|mp4|webm)$'
);
create policy portfolio_media_select on storage.objects for select to authenticated
using (bucket_id = 'project-media');
-- Cleanup may remove only the caller's unregistered uploads. Published objects are immutable.
create policy portfolio_media_cleanup on storage.objects for delete to authenticated
using (
  bucket_id = 'project-media'
  and split_part(name, '/', 1) = (select auth.uid())::text
  and not exists (select 1 from public.project_media m where m.object_path = name)
);

create function public.create_portfolio_project(p_request_id uuid, p_project jsonb, p_media jsonb)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_id integer;
  v_item jsonb;
  v_path text;
  v_kind text;
  v_meta jsonb;
  v_bytes bigint;
  v_total bigint := 0;
  v_mime text;
begin
  if v_user is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_request_id is null or jsonb_typeof(p_project) is distinct from 'object'
      or jsonb_typeof(p_media) is distinct from 'array' then
    raise exception 'Invalid request' using errcode = '22023';
  end if;

  -- Serialize retries for this request; the project and all media commit together.
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_request_id::text, 0));
  select id into v_id from public.projects where request_id = p_request_id and created_by = v_user;
  if found then return v_id; end if;

  if jsonb_array_length(p_media) not between 1 and 26
      or (select count(*) from jsonb_array_elements(p_media) m where m->>'kind' = 'main') <> 1
      or (select count(*) from jsonb_array_elements(p_media) m where m->>'kind' = 'video') > 1
      or (select count(*) from jsonb_array_elements(p_media) m where m->>'kind' = 'gallery') > 12
      or (select count(*) from jsonb_array_elements(p_media) m where m->>'kind' = 'application') > 12 then
    raise exception 'Invalid media count' using errcode = '22023';
  end if;

  for v_item in select * from jsonb_array_elements(p_media) loop
    v_path := v_item->>'object_path';
    v_kind := v_item->>'kind';
    if v_path is null or v_kind is null or v_kind not in ('main', 'gallery', 'application', 'video')
        or split_part(v_path, '/', 1) <> v_user::text
        or split_part(v_path, '/', 2) <> p_request_id::text then
      raise exception 'Invalid media path' using errcode = '22023';
    end if;
    -- Lock the actual object: do not trust size/MIME sent by the browser.
    select metadata into v_meta from storage.objects
      where bucket_id = 'project-media' and name = v_path for update;
    if not found then raise exception 'Media not uploaded' using errcode = '22023'; end if;
    v_bytes := (v_meta->>'size')::bigint;
    v_mime := v_meta->>'mimetype';
    if v_bytes is null or v_bytes <= 0 or v_mime is null then
      raise exception 'Invalid media metadata' using errcode = '22023';
    end if;
    if v_kind = 'video' then
      if v_bytes > 104857600 or not (
        (v_mime = 'video/mp4' and v_path ~ '\.mp4$') or
        (v_mime = 'video/webm' and v_path ~ '\.webm$')
      ) then raise exception 'Invalid video' using errcode = '22023'; end if;
    else
      if v_bytes > 10485760 or not (
        (v_mime = 'image/jpeg' and v_path ~ '\.jpg$') or
        (v_mime = 'image/png' and v_path ~ '\.png$') or
        (v_mime = 'image/webp' and v_path ~ '\.webp$')
      ) then raise exception 'Invalid image' using errcode = '22023'; end if;
    end if;
    v_total := v_total + v_bytes;
  end loop;
  if v_total > 157286400 then raise exception 'Media total exceeded' using errcode = '22023'; end if;

  insert into public.projects (request_id, created_by, title, slug, category_id, description, location, year, status)
  values (p_request_id, v_user, btrim(p_project->>'title'), p_project->>'slug',
    (p_project->>'category_id')::integer, btrim(coalesce(p_project->>'description', '')),
    btrim(coalesce(p_project->>'location', '')), (p_project->>'year')::integer, p_project->>'status')
  returning id into v_id;
  insert into public.project_media (project_id, kind, position, object_path)
  select v_id, m->>'kind', (m->>'position')::integer, m->>'object_path'
  from jsonb_array_elements(p_media) m;
  return v_id;
end;
$$;
revoke all on function public.create_portfolio_project(uuid, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.create_portfolio_project(uuid, jsonb, jsonb) to authenticated;

notify pgrst, 'reload schema';
commit;
